USE [master]
GO
/****** Object:  Database [MiniCoreSahid]    Script Date: 31/1/2023 22:41:34 ******/
CREATE DATABASE [MiniCoreSahid]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MiniCoreSahid', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MiniCoreSahid.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MiniCoreSahid_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MiniCoreSahid_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MiniCoreSahid] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MiniCoreSahid].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MiniCoreSahid] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET ARITHABORT OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MiniCoreSahid] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MiniCoreSahid] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MiniCoreSahid] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MiniCoreSahid] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MiniCoreSahid] SET  MULTI_USER 
GO
ALTER DATABASE [MiniCoreSahid] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MiniCoreSahid] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MiniCoreSahid] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MiniCoreSahid] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MiniCoreSahid] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MiniCoreSahid] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MiniCoreSahid] SET QUERY_STORE = OFF
GO
USE [MiniCoreSahid]
GO
/****** Object:  Table [dbo].[Clientes]    Script Date: 31/1/2023 22:41:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clientes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Contratos]    Script Date: 31/1/2023 22:41:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contratos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](150) NOT NULL,
	[ClientId] [int] NOT NULL,
	[Montos] [int] NOT NULL,
	[Fecha] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[vw_Contratos]    Script Date: 31/1/2023 22:41:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
	CREATE VIEW [dbo].[vw_Contratos] AS
	SELECT cl.Name, SUM(c.Montos) Totales FROM Contratos c
	INNER JOIN Clientes cl ON c.ClientId = cl.Id
	GROUP BY cl.Id, cl.Name
GO
ALTER TABLE [dbo].[Contratos]  WITH CHECK ADD  CONSTRAINT [FKClientesContratos] FOREIGN KEY([ClientId])
REFERENCES [dbo].[Clientes] ([Id])
GO
ALTER TABLE [dbo].[Contratos] CHECK CONSTRAINT [FKClientesContratos]
GO
USE [master]
GO
ALTER DATABASE [MiniCoreSahid] SET  READ_WRITE 
GO
